#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/ndnSIM-module.h"
#include "ns3/point-to-point-module.h"
#include <ns3/ndnSIM/utils/tracers/ndn-cs-tracer.h>
#include <ns3/ndnSIM/utils/tracers/ndn-app-delay-tracer.h>
using namespace ns3;

int main (int argc, char *argv[])
{
  // Read optional command-line parameters (e.g., enable visualizer with ./waf --run=<> --visualize
  // setting default parameters for PointToPoint links and channels
  Config::SetDefault ("ns3::PointToPointNetDevice::DataRate", StringValue ("100Mbps"));
  Config::SetDefault ("ns3::PointToPointChannel::Delay", StringValue ("0.1ms"));
  Config::SetDefault ("ns3::DropTailQueue::MaxPackets", StringValue ("100"));
  CommandLine cmd;
  cmd.Parse (argc, argv);
  PointToPointHelper p2p;
  // Creating nodes
  AnnotatedTopologyReader topologyReader ("", 10);
  topologyReader.SetFileName ("topo/line.txt");
  topologyReader.Read ();


  
  /*Ptr<Node> Node1 = CreateObject<Node> ();
  Ptr<Node> Node2 = CreateObject<Node> ();
  Ptr<Node> Node3 = CreateObject<Node> ();
  Ptr<Node> Node4 = CreateObject<Node> ();
  Ptr<Node> Node5 = CreateObject<Node> ();
  Ptr<Node> Node6 = CreateObject<Node> ();
  Ptr<Node> Node7 = CreateObject<Node> ();
  p2p.Install(Node1, Node2);
  p2p.Install(Node1, Node3);
  p2p.Install(Node2, Node4);
  p2p.Install(Node2, Node6);
  p2p.Install(Node3, Node4);
  p2p.Install(Node3, Node7);
  p2p.Install(Node4, Node5);
  p2p.Install(Node5, Node6);
  p2p.Install(Node5, Node7);*/

  // Install CCNx stack on all nodes
  ndn::StackHelper ccnxHelper;
  ccnxHelper.SetDefaultRoutes(true);
  //ccnxHelper.InstallAll ();
  // Installing applications
  ccnxHelper.SetPit ("ns3::ndn::pit::Lru","MaxSize", "1000");
  ccnxHelper.SetContentStore ("ns3::ndn::cs::Lru","MaxSize", "1000");
  ccnxHelper.SetForwardingStrategy ("ns3::ndn::fw::Flooding");
  //ccnxHelper.SetForwardingStrategy ("ns3::ndn::fw::BestRoute");
  //ccnxHelper.SetForwardingStrategy ("ns3::ndn::fw::SmartFlooding");
  ccnxHelper.InstallAll ();
  
  // Installing global routing interface on all nodes
  ndn::GlobalRoutingHelper ccnxGlobalRoutingHelper;
  ccnxGlobalRoutingHelper.InstallAll ();
  //Add /prefix origins to ndn::GlobalRouter
  /*ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node1);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node2);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node3);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node4);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node5);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node6);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node7);*/
  //ccnxGlobalRoutingHelper.CalculateRoutes ();
  
  Ptr<Node> Node1 = Names::Find<Node>("Node1");
  Ptr<Node> Node6 = Names::Find<Node>("Node6");
  Ptr<Node> Node7 = Names::Find<Node>("Node7");
  Ptr<Node> Node2 = Names::Find<Node>("Node2");
  Ptr<Node> Node3 = Names::Find<Node>("Node3");
  Ptr<Node> Node4 = Names::Find<Node>("Node4");
  Ptr<Node> Node5 = Names::Find<Node>("Node5");
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node1);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node2);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node3);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node4);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node5);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node6);
  ccnxGlobalRoutingHelper.AddOrigins ("/ndn/vod/nc", Node7);

  ndn::AppHelper Client("ns3::ndn::ConsumerCbr");
  Client.SetPrefix("/ndn/vod/nc");
  Client.SetAttribute("Frequency", StringValue("100"));
  Client.Install (Node6);
  Client.Install (Node7);
  Client.Install (Node3);
  Client.Install (Node4);
  Client.Install (Node5);

  
  /*ndn::AppHelper producer("ns3::ndn::Producer");
  producer.SetPrefix("/ndn/vod/nc");
  producer.SetAttribute("PayloadSize", StringValue("1024"));
  producer.Install (Node1);*/
  //ccnxGlobalRoutingHelper.CalculateRoutes ();
  //ApplicationContainer app4 = producer.Install(node4);
  //ApplicationContainer app4 = producer.Install(node4);
  //ApplicationContainer app4 = producer.Install(node4);
  //ApplicationContainer app4 = producer.Install(node4);
  
  ndn::AppHelper consumerHelper ("NetworkCodingApp");
  //ApplicationContainer app1 = consumerHelper.Install (node1); 
  //ApplicationContainer app2 = consumerHelper.Install (node2);
  //ApplicationContainer app3 = consumerHelper.Install (node3);
  //ApplicationContainer app1 = producer.Install (node1);
  consumerHelper.Install (Node1);
  ccnxGlobalRoutingHelper.CalculateRoutes ();
  //app1.Start(Seconds (0.0)); // will send out Interest, which nobody will receive (Interests generated by an app will not got back to the app)
  //app1.Stop(Seconds(20.0));
  //app6.Start (Seconds (1.0)); // will send out an Interests, which will be received and satisfied by app1
  //app7.Start (Seconds (1.0));
  boost::tuple< boost::shared_ptr<std::ostream>, std::list<Ptr<ndn::L3AggregateTracer> > >
  AggregateTracer = ndn::L3AggregateTracer::InstallAll ("line/aggregate-trace.txt", Seconds (0.5));
 
  boost::tuple< boost::shared_ptr<std::ostream>, std::list<Ptr<ndn::L3RateTracer> > >
  L3RateTracer = ndn::L3RateTracer::InstallAll ("line/rate-trace.txt", Seconds (0.5));
 
  boost::tuple< boost::shared_ptr<std::ostream>, std::list<Ptr<ndn::CsTracer> > >
  aggTracers = ndn::CsTracer::InstallAll ("line/cs-trace.txt", Seconds (1));
 
  boost::tuple< boost::shared_ptr<std::ostream>, std::list<Ptr<ndn::AppDelayTracer> > >
  delayTracer = ndn::AppDelayTracer::InstallAll ("line/app-delays-trace.txt");

  Simulator::Stop (Seconds (20.0));
  Simulator::Run ();
  Simulator::Destroy ();
  return 0;
}
